### ISSUE TITLE
Goal set-up fails with Maven 3.1.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javahelp/fitnesse-launcher-maven-plugin#26]
Originally reported on Google Code with ID 26

```
Running fitnesse-launcher-maven-plugin:1.3.0:set-up fails with

[ERROR] Failed to execute goal uk.co.javahelp.fitnesse:fitnesse-launcher-maven-plugin:1.3.0:set-up
(fitnesse-tests) on project fitnesse-integration-test: Execution fitnesse-tests of
goal uk.co.javahelp.fitnesse:fitnesse-launcher-maven-plugin:1.3.0:set-up failed: An
API incompatibility was encountered while executing uk.co.javahelp.fitnesse:fitnesse-launcher-maven-plugin:1.3.0:set-up:
java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/sonatype/aether/RepositorySystemSession;

Maven 3.1.1
Mac OS X 10.8.5
Java(TM) SE Runtime Environment (build 1.7.0_21-b12)

It works with maven 3.0.4.
```

Reported by `daniel.marell` on 2013-11-19 22:22:24
